// Code generated by oto; DO NOT EDIT.

package server

import (
	"fmt"
	"strings"

	"go.uber.org/zap"

	"github.com/dashotv/grimoire"
)

func setupDatabase(s *Server) error {
	db := &connection{
		log: s.Logger.Named("db"),
	}

	dbname := s.Config.Name + "_development"
	if s.Config.Production {
		dbname = s.Config.Name + "_production"
	}

	if col, err := grimoire.New[*File](s.Config.Mongo, dbname, strings.ToLower("File")); err != nil {
		return fmt.Errorf("failed to create File collection: %w", err)
	} else {
		db.File = col
		grimoire.Indexes(col, &File{})
	}

	if col, err := grimoire.New[*Job](s.Config.Mongo, dbname, strings.ToLower("Job")); err != nil {
		return fmt.Errorf("failed to create Job collection: %w", err)
	} else {
		db.Job = col
		grimoire.Indexes(col, &Job{})
	}

	s.db = db
	return nil
}

type connection struct {
	log *zap.SugaredLogger

	File *grimoire.Store[*File]

	Job *grimoire.Store[*Job]
}

type EmptyResponse struct {
	// Error is string explaining what went wrong. Empty if everything was fine.
	Error string `json:"error,omitempty"`
}

// File represents a file in the file system.
type File struct { // model
	grimoire.Document `bson:",inline"` // includes default model settings
	//ID        primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	//CreatedAt time.Time          `bson:"created_at" json:"created_at"`
	//UpdatedAt time.Time          `bson:"updated_at" json:"updated_at"`
	Path       string `json:"path" bson:"path" grimoire:"index" `
	Size       int64  `json:"size" bson:"size" `
	ModifiedAt int64  `bson:"modified_at" grimoire:"index" json:"modified_at" `
}

type FilesResponse struct {
	Count  int64   `json:"count"`
	Result []*File `json:"files"`
	// Error is string explaining what went wrong. Empty if everything was fine.
	Error string `json:"error,omitempty"`
}

type IndexRequest struct {
	Limit int `json:"limit"`
	Skip  int `json:"skip"`
}

// Job tracks jobs in the system
type Job struct { // model
	grimoire.Document `bson:",inline"` // includes default model settings
	//ID        primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	//CreatedAt time.Time          `bson:"created_at" json:"created_at"`
	//UpdatedAt time.Time          `bson:"updated_at" json:"updated_at"`
	Kind     string        `json:"kind" bson:"kind" `
	Args     string        `json:"args" bson:"args" `
	Status   string        `json:"status" bson:"status" `
	Queue    string        `json:"queue" bson:"queue" `
	Attempts []*JobAttempt `bson:"attempts" json:"attempts" `
}

// JobAttempt tracks the attempts made to process a job
type JobAttempt struct {
	StartedAt  string   `json:"started_at"`
	Duration   float64  `json:"duration"`
	Status     string   `json:"status"`
	Error      string   `json:"error"`
	Stacktrace []string `json:"stacktrace"`
}

type JobResponse struct {
	Job *Job `json:"job"`
	// Error is string explaining what went wrong. Empty if everything was fine.
	Error string `json:"error,omitempty"`
}

type JobsResponse struct {
	Total   int64  `json:"total"`
	Results []*Job `json:"results"`
	// Error is string explaining what went wrong. Empty if everything was fine.
	Error string `json:"error,omitempty"`
}

type KeyRequest struct {
	Key string `json:"id"`
}

type Request struct {
	ID    string `json:"id"`
	Limit int    `json:"limit"`
	Skip  int    `json:"skip"`
}
